<?php declare(strict_types=1); ?>
<?php
$summary = is_array($summary ?? null) ? $summary : [];
$currencies = is_array($currencies ?? null) ? $currencies : [];
$recentQuotes = is_array($recentQuotes ?? null) ? $recentQuotes : [];
$recentTransactions = is_array($recentTransactions ?? null) ? $recentTransactions : [];
$convertError = (string)($convertError ?? '');
?>
<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h1 class="h3 mb-1">Convert</h1>
        <p class="text-secondary mb-0">Instantly convert between supported assets at a fixed spread.</p>
    </div>
    <div class="d-flex gap-2">
        <a href="/dashboard" class="btn btn-outline-light btn-sm">Dashboard</a>
        <a href="/trading" class="btn btn-outline-info btn-sm">Trading</a>
    </div>
</div>

<?php if ($convertError !== ''): ?>
    <div class="alert alert-warning"><?= e($convertError) ?></div>
<?php endif; ?>

<!-- Summary KPIs -->
<div class="row g-3 mb-4">
    <?php
    $kpis = [
        ['label' => 'Total Conversions', 'value' => number_format((int)($summary['total_conversions'] ?? 0)), 'color' => 'info'],
        ['label' => 'Pending Quotes', 'value' => number_format((int)($summary['pending_quotes'] ?? 0)), 'color' => 'warning'],
        ['label' => 'Total Fees Paid', 'value' => number_format((float)($summary['total_fees_paid'] ?? 0), 8), 'color' => 'secondary'],
        ['label' => 'Available Currencies', 'value' => number_format((int)($summary['available_currencies'] ?? 0)), 'color' => 'success'],
    ];
    foreach ($kpis as $kpi):
    ?>
    <div class="col-md-3 col-6">
        <div class="glass rounded-4 p-3 text-center">
            <div class="h4 fw-bold text-<?= e($kpi['color']) ?>"><?= $kpi['value'] ?></div>
            <div class="small text-secondary"><?= e($kpi['label']) ?></div>
        </div>
    </div>
    <?php endforeach; ?>
</div>

<div class="row g-3 mb-4">
    <!-- Convert Widget -->
    <div class="col-lg-5">
        <div class="glass rounded-4 p-3">
            <h2 class="h6 mb-3">Get a Quote</h2>
            <p class="small text-secondary mb-3">
                Select the currencies and amount to preview a conversion. Quotes are valid for a limited time.
                Contact support or use the trading page to execute live orders.
            </p>
            <div class="row g-3">
                <div class="col-12">
                    <label class="form-label small">From Currency</label>
                    <select class="form-select">
                        <option value="">Select currency</option>
                        <?php foreach ($currencies as $cur): ?>
                            <option value="<?= (int)($cur['id'] ?? 0) ?>"><?= e((string)($cur['code'] ?? '')) ?> — <?= e((string)($cur['name'] ?? '')) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-12">
                    <label class="form-label small">To Currency</label>
                    <select class="form-select">
                        <option value="">Select currency</option>
                        <?php foreach ($currencies as $cur): ?>
                            <option value="<?= (int)($cur['id'] ?? 0) ?>"><?= e((string)($cur['code'] ?? '')) ?> — <?= e((string)($cur['name'] ?? '')) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="col-12">
                    <label class="form-label small">Amount</label>
                    <input class="form-control" type="number" step="any" min="0" placeholder="0.00000000">
                </div>
                <div class="col-12">
                    <div class="glass rounded-3 p-3 text-center text-secondary small">
                        Live quotes are generated by the trading engine. Check back once trading pairs are configured.
                    </div>
                </div>
            </div>
        </div>

        <!-- Available Currencies -->
        <div class="glass rounded-4 p-3 mt-3">
            <h2 class="h6 mb-3">Supported Currencies</h2>
            <div class="d-flex flex-wrap gap-2">
                <?php foreach ($currencies as $cur): ?>
                    <span class="badge text-bg-secondary"><?= e((string)($cur['code'] ?? '-')) ?></span>
                <?php endforeach; ?>
                <?php if ($currencies === []): ?><span class="text-secondary small">No currencies configured.</span><?php endif; ?>
            </div>
        </div>
    </div>

    <!-- Recent Quotes -->
    <div class="col-lg-7">
        <div class="glass rounded-4 p-3 mb-3">
            <h2 class="h6 mb-3">Recent Quotes</h2>
            <div class="table-responsive">
                <table class="table table-dark table-sm align-middle mb-0">
                    <thead>
                        <tr>
                            <th>From</th>
                            <th>To</th>
                            <th>From Amount</th>
                            <th>To Amount</th>
                            <th>Rate</th>
                            <th>Spread</th>
                            <th>Status</th>
                            <th>Expires</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($recentQuotes as $quote): ?>
                        <tr>
                            <td><span class="badge text-bg-secondary"><?= e((string)($quote['from_currency'] ?? '-')) ?></span></td>
                            <td><span class="badge text-bg-info"><?= e((string)($quote['to_currency'] ?? '-')) ?></span></td>
                            <td><?= number_format((float)($quote['from_amount'] ?? 0), 8) ?></td>
                            <td><?= number_format((float)($quote['to_amount'] ?? 0), 8) ?></td>
                            <td class="small"><?= number_format((float)($quote['quoted_rate'] ?? 0), 8) ?></td>
                            <td class="small text-secondary"><?= number_format((float)($quote['spread_percent'] ?? 0), 4) ?>%</td>
                            <td>
                                <span class="badge text-bg-<?= match($quote['status'] ?? '') {
                                    'executed' => 'success',
                                    'pending' => 'warning text-dark',
                                    'expired' => 'secondary',
                                    'cancelled' => 'danger',
                                    default => 'secondary'
                                } ?>"><?= e((string)($quote['status'] ?? '-')) ?></span>
                            </td>
                            <td class="small text-secondary"><?= e((string)($quote['expires_at'] ?? '-')) ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <?php if ($recentQuotes === []): ?><tr><td colspan="8" class="text-center text-secondary">No quotes yet.</td></tr><?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Transaction History -->
<div class="glass rounded-4 p-3">
    <h2 class="h6 mb-3">Conversion History</h2>
    <div class="table-responsive">
        <table class="table table-dark table-sm align-middle mb-0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>From</th>
                    <th>To</th>
                    <th>From Amount</th>
                    <th>To Amount</th>
                    <th>Executed Rate</th>
                    <th>Fee</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($recentTransactions as $tx): ?>
                <tr>
                    <td><?= (int)($tx['id'] ?? 0) ?></td>
                    <td><span class="badge text-bg-secondary"><?= e((string)($tx['from_currency'] ?? '-')) ?></span></td>
                    <td><span class="badge text-bg-info"><?= e((string)($tx['to_currency'] ?? '-')) ?></span></td>
                    <td><?= number_format((float)($tx['from_amount'] ?? 0), 8) ?></td>
                    <td><?= number_format((float)($tx['to_amount'] ?? 0), 8) ?></td>
                    <td class="small"><?= number_format((float)($tx['executed_rate'] ?? 0), 8) ?></td>
                    <td class="small text-secondary"><?= number_format((float)($tx['fee_amount'] ?? 0), 8) ?></td>
                    <td class="small text-secondary"><?= e((string)($tx['created_at'] ?? '-')) ?></td>
                </tr>
            <?php endforeach; ?>
            <?php if ($recentTransactions === []): ?><tr><td colspan="8" class="text-center text-secondary">No conversions yet.</td></tr><?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
